/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.presentation.TelaNotaAluno;

import br.maua.config.IconUtil;
import br.maua.domain.Aluno;
import br.maua.infrastructure.DAO.AlunoDAO;
import br.maua.presentation.TelaModalPerfilAluno.ModalPerfilAluno;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Luiza
 */
public class TelaNotaAluno extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                .getLogger(TelaNotaAluno.class.getName());
        private final Aluno aluno;
        private final ModalPerfilAluno modalOrigem;

        /**
         * Creates new form TelaNotaAluno
         */
        public TelaNotaAluno(Aluno aluno, ModalPerfilAluno modalOrigem) {
                this.aluno = aluno;
                this.modalOrigem = modalOrigem;
                this.setIconImages(IconUtil.ICONS);
                this.setTitle("Jornada Mauá");
                initComponents();
                carregarNotas();
                this.setVisible(true);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPopupMenu1 = new javax.swing.JPopupMenu();
                jScrollPane1 = new javax.swing.JScrollPane();
                painelAzul = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                tabelaNotas = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                painelAzul.setBackground(new java.awt.Color(19, 112, 178));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Suas Notas");

                jButton1.setBackground(new java.awt.Color(240, 147, 32));
                jButton1.setForeground(new java.awt.Color(255, 255, 255));
                jButton1.setText("Voltar");
                jButton1.addActionListener(this::jButton1ActionPerformed);

                tabelaNotas.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                                "Atividade", "Nota"
                        }) {
                        final Class[] types = new Class[]{
                                java.lang.Object.class, java.lang.Float.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jScrollPane2.setViewportView(tabelaNotas);

                javax.swing.GroupLayout painelAzulLayout = new javax.swing.GroupLayout(painelAzul);
                painelAzul.setLayout(painelAzulLayout);
                painelAzulLayout.setHorizontalGroup(
                        painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelAzulLayout.createSequentialGroup()
                                        .addGroup(painelAzulLayout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(painelAzulLayout
                                                        .createSequentialGroup()
                                                        .addGap(16, 16, 16)
                                                        .addComponent(jButton1)
                                                        .addGap(266, 266, 266)
                                                        .addComponent(jLabel1))
                                                .addGroup(painelAzulLayout
                                                        .createSequentialGroup()
                                                        .addGap(130, 130, 130)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                760,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(134, Short.MAX_VALUE)));
                painelAzulLayout.setVerticalGroup(
                        painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelAzulLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(
                                                painelAzulLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addGroup(painelAzulLayout
                                                                .createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton1)))
                                        .addGap(55, 55, 55)
                                        .addComponent(jScrollPane2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                509,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(170, Short.MAX_VALUE)));

                jScrollPane1.setViewportView(painelAzul);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1,
                                        javax.swing.GroupLayout.Alignment.TRAILING));
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768,
                                        Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                modalOrigem.getTelaAnterior().setVisible(true);
                dispose();
        }// GEN-LAST:event_jButton1ActionPerformed

        private void carregarNotas() {
                DefaultTableModel modelo = (DefaultTableModel) tabelaNotas.getModel();
                tabelaNotas.setEnabled(false);

                new SwingWorker<Map<String, Float>, Void>() {
                        @Override
                        protected Map<String, Float> doInBackground() throws Exception {
                                return AlunoDAO.obterNotas(aluno);
                        }

                        @Override
                        protected void done() {
                                try {
                                        Map<String, Float> notas = get();

                                        for (Map.Entry<String, Float> tarefa_nota : notas.entrySet()) {
                                                modelo.addRow(new Object[]{tarefa_nota.getKey(),
                                                        tarefa_nota.getValue()});
                                        }
                                } catch (Exception ex) {
                                        Logger.getLogger(TelaNotaAluno.class.getName()).log(Level.SEVERE, null, ex);
                                        JOptionPane.showMessageDialog(null, "Erro ao buscar notas", "Erro!",
                                                JOptionPane.ERROR_MESSAGE);
                                }
                        }
                }.execute();
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPopupMenu jPopupMenu1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JPanel painelAzul;
        private javax.swing.JTable tabelaNotas;
        // End of variables declaration//GEN-END:variables
}
