/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.presentation.TelaCriarTarefa;

/**
 *
 * @author Lenovo
 */
public class TelaCriarTarefa2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCriarTarefa2.class.getName());

    /**
     * Creates new form TelaCriarTarefa2
     */
    public TelaCriarTarefa2() {
        initComponents();
        
        // 1. Remove os componentes do painel para reinserir com os gaps na ordem certa
        painelConteudo.removeAll();
        
        // 2. Readiciona os blocos estruturais intercalando com os gaps
        painelConteudo.add(jPanel1); // Espaço do topo (Margem)
        
        painelConteudo.add(jPanel2); // Bloco Azul do Título
        painelConteudo.add(javax.swing.Box.createVerticalStrut(20)); // Gap de 20px
        
        painelConteudo.add(jPanel3); // Bloco de Configurações (Prazo/Explorador)
        painelConteudo.add(javax.swing.Box.createVerticalStrut(20)); // Gap de 20px
        
        //painelConteudo.add(jPanel7); // Questão 1 (Múltipla Escolha)
        //painelConteudo.add(javax.swing.Box.createVerticalStrut(20)); // Gap de 20px
        
        //painelConteudo.add(jPanel9); // Questão 2 (Dissertativa)
        //painelConteudo.add(javax.swing.Box.createVerticalStrut(20)); // Gap de 20px
        
        //painelConteudo.add(jPanel11); // Questão 3 (Múltipla Escolha)
        //painelConteudo.add(javax.swing.Box.createVerticalStrut(20)); // Gap de 20px
        
        painelConteudo.add(jPanel15); // Botão "+ Adicionar Questão"
        painelConteudo.add(javax.swing.Box.createVerticalStrut(40));

        
        painelConteudo.revalidate();
        painelConteudo.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        painelConteudo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelConteudo.setBackground(new java.awt.Color(255, 255, 255));
        painelConteudo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 112, 178), 30));
        painelConteudo.setMaximumSize(new java.awt.Dimension(32827, 32827));
        painelConteudo.setLayout(new javax.swing.BoxLayout(painelConteudo, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        painelConteudo.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(19, 112, 178));
        jPanel2.setMaximumSize(new java.awt.Dimension(592, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Novo Questionário");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        painelConteudo.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(19, 112, 178));
        jPanel3.setMaximumSize(new java.awt.Dimension(630, 160));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox2, 0, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField1.addActionListener(this::jFormattedTextField1ActionPerformed);

        jLabel2.setText("Prazo:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        painelConteudo.add(jPanel3);

        jPanel15.setBackground(new java.awt.Color(19, 112, 178));
        jPanel15.setMaximumSize(new java.awt.Dimension(400, 68));
        jPanel15.setPreferredSize(new java.awt.Dimension(600, 222));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("+ Adicionar Questão");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel6)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        painelConteudo.add(jPanel15);

        jScrollPane1.setViewportView(painelConteudo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked

    int numeroQuestao = 1;
    for (java.awt.Component c : painelConteudo.getComponents()) {
        if (c instanceof javax.swing.JPanel && c != jPanel1 && c != jPanel2 && c != jPanel3 && c != jPanel15) {
            numeroQuestao++;
        }
    }

    // 2. Cria o painel da nova questão completo usando o nosso método auxiliar
    javax.swing.JPanel novaQuestaoCompleta = criarPainelNovaQuestao(numeroQuestao);
    jPanel15.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    // 3. Remove o botão de adicionar temporariamente para ele ir para o fim da fila
    painelConteudo.remove(jPanel15);
    
    // 4. Adiciona o espaçador e a nova questão montada
    painelConteudo.add(javax.swing.Box.createVerticalStrut(20)); 
    painelConteudo.add(novaQuestaoCompleta);
    
    // 5. Devolve o botão e os espaçadores de segurança para o final do painel
    painelConteudo.add(javax.swing.Box.createVerticalStrut(20)); 
    painelConteudo.add(jPanel15);
    painelConteudo.add(javax.swing.Box.createVerticalStrut(40)); 
    
    // 6. Atualiza a tela e força o scroll a descer
    painelConteudo.revalidate();
    painelConteudo.repaint();
    
    javax.swing.SwingUtilities.invokeLater(() -> {
        jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
    });
    }//GEN-LAST:event_jPanel15MouseClicked
    
    private javax.swing.JPanel criarPainelNovaQuestao(int numero) {
        javax.swing.JPanel painelQuestao = new javax.swing.JPanel();
        painelQuestao.setBackground(new java.awt.Color(240, 147, 32));
        painelQuestao.setLayout(new javax.swing.BoxLayout(painelQuestao, javax.swing.BoxLayout.Y_AXIS));
        painelQuestao.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 20, 25));
        
        painelQuestao.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        painelQuestao.setMaximumSize(new java.awt.Dimension(632, 380));
        painelQuestao.setPreferredSize(new java.awt.Dimension(632, 380));

        javax.swing.JLabel lblTitulo = new javax.swing.JLabel("Questão - " + numero);
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18));
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        painelQuestao.add(lblTitulo);
        painelQuestao.add(javax.swing.Box.createVerticalStrut(10));

        javax.swing.JComboBox<String> comboTipo = new javax.swing.JComboBox<>(new String[] { "Múltipla Escolha", "Dissertativa" });
        comboTipo.setMaximumSize(new java.awt.Dimension(580, 35));
        comboTipo.setPreferredSize(new java.awt.Dimension(580, 35));
        comboTipo.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        painelQuestao.add(comboTipo);
        painelQuestao.add(javax.swing.Box.createVerticalStrut(15));

        javax.swing.JTextArea txtEnunciado = new javax.swing.JTextArea(4, 20);
        txtEnunciado.setText("Digite o enunciado da questão aqui...");
        txtEnunciado.setFont(new java.awt.Font("Segoe UI", 0, 14));
        txtEnunciado.setLineWrap(true);
        txtEnunciado.setWrapStyleWord(true);

        javax.swing.JScrollPane scrollEnunciado = new javax.swing.JScrollPane(txtEnunciado);
        scrollEnunciado.setMaximumSize(new java.awt.Dimension(580, 80));
        scrollEnunciado.setPreferredSize(new java.awt.Dimension(580, 80));
        scrollEnunciado.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        painelQuestao.add(scrollEnunciado);
        painelQuestao.add(javax.swing.Box.createVerticalStrut(15));

        javax.swing.JPanel painelDinamico = new javax.swing.JPanel();
        painelDinamico.setBackground(new java.awt.Color(240, 147, 32));
        painelDinamico.setLayout(new javax.swing.BoxLayout(painelDinamico, javax.swing.BoxLayout.Y_AXIS));
        painelDinamico.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        painelQuestao.add(painelDinamico);

        java.lang.Runnable atualizarCampos = () -> {
            painelDinamico.removeAll();
            String tipo = (String) comboTipo.getSelectedItem();

            if ("Múltipla Escolha".equals(tipo)) {
                // Cria as 4 alternativas com RadioButtons idênticos ao seu print
                javax.swing.ButtonGroup grupoRadio = new javax.swing.ButtonGroup();
                for (int i = 1; i <= 4; i++) {
                    javax.swing.JRadioButton radio = new javax.swing.JRadioButton("Escreva Alternativa");
                    radio.setFont(new java.awt.Font("Segoe UI", 0, 14));
                    radio.setForeground(new java.awt.Color(255, 255, 255));
                    radio.setBackground(new java.awt.Color(240, 147, 32));
                    radio.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

                    grupoRadio.add(radio);
                    painelDinamico.add(radio);
                    painelDinamico.add(javax.swing.Box.createVerticalStrut(5));
                }
                painelQuestao.setMaximumSize(new java.awt.Dimension(632, 380));
                painelQuestao.setPreferredSize(new java.awt.Dimension(632, 380));
            } else {
                javax.swing.JLabel lblResposta = new javax.swing.JLabel("Resposta:");
                lblResposta.setFont(new java.awt.Font("Segoe UI", 0, 14));
                lblResposta.setForeground(new java.awt.Color(255, 255, 255));
                lblResposta.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
                painelDinamico.add(lblResposta);
                painelDinamico.add(javax.swing.Box.createVerticalStrut(5));

                javax.swing.JTextArea txtResposta = new javax.swing.JTextArea(3, 20);
                txtResposta.setEditable(false); // Geralmente o professor não responde nela
                javax.swing.JScrollPane scrollResposta = new javax.swing.JScrollPane(txtResposta);
                scrollResposta.setMaximumSize(new java.awt.Dimension(580, 60));
                scrollResposta.setPreferredSize(new java.awt.Dimension(580, 60));
                scrollResposta.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

                painelDinamico.add(scrollResposta);
                painelQuestao.setMaximumSize(new java.awt.Dimension(632, 340));
                painelQuestao.setPreferredSize(new java.awt.Dimension(632, 340));
            }

            painelQuestao.revalidate();
            painelQuestao.repaint();
        };

        comboTipo.addActionListener(e -> atualizarCampos.run());

        atualizarCampos.run();

        return painelQuestao;
}
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCriarTarefa2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelConteudo;
    // End of variables declaration//GEN-END:variables
}
