/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.presentation.TelaQuestionarioAluno;

import java.awt.Component;
import java.io.File;
import java.sql.SQLException;
import java.util.List;

import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

import static br.maua.config.AppConfig.BASE_ALUNO;
import br.maua.domain.Aluno;
import br.maua.domain.Questao;
import br.maua.domain.QuestaoAlternativa;
import br.maua.domain.QuestaoDissertativa;
import br.maua.domain.QuestaoUpload;
import br.maua.domain.Resposta;
import br.maua.domain.RespostaAlternativa;
import br.maua.domain.RespostaDissertativa;
import br.maua.domain.RespostaUpload;
import br.maua.domain.Tarefa;
import br.maua.domain.Tentativa;
import br.maua.infrastructure.DAO.QuestaoDAO;
import br.maua.infrastructure.DAO.RespostaAlternativaDAO;
import br.maua.infrastructure.DAO.RespostaDAO;
import br.maua.infrastructure.DAO.RespostaDissertativaDAO;
import br.maua.infrastructure.DAO.RespostaUploadDAO;
import br.maua.service.ArquivoService;

/**
 *
 * @author Luiza
 */
public class TelaQuestionarioAluno extends javax.swing.JFrame {


    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger
    (TelaQuestionarioAluno.class.getName());
    private final Tarefa tarefa;
    private Aluno aluno;
    private final Tentativa tentativa;

    /**
     * Creates new form TelaQuestionarioAluno
     */
    public TelaQuestionarioAluno(Tarefa tarefa, Tentativa tentativa, Aluno aluno) {
        this.tarefa = tarefa;
        this.tentativa = tentativa;
        this.aluno = aluno;
        initComponents();
        try{
            QuestaoDAO.buscarPorTarefa(tarefa);
        }catch(SQLException e ){
            JOptionPane.showMessageDialog(rootPane, "Erro ao se comunicar com o banco!", "Erro", JOptionPane.ERROR_MESSAGE);
        }

        titulo3.setText(tarefa.getTitulo());

        PainelQuestoes.setLayout(
            new BoxLayout(
                PainelQuestoes,
                BoxLayout.Y_AXIS
            )
        );

        try {
        carregarQuestoes(tarefa.getQuestoes());

        } catch (Exception e) {
        e.printStackTrace();
        }

        painelAzul1.setLayout(new java.awt.GridBagLayout());
        painelAzul1.add(painelCinza1);
        jScrollPane6.getVerticalScrollBar().setUnitIncrement(25);
        configurarScroll();
        
    }
    
    

    private void carregarQuestoes(List<Questao>questoes){
        for (Questao q : questoes){
            if (q instanceof QuestaoDissertativa qd){
                PainelQuestoes.add(
                    new PainelQuestaoDissertativa(qd)
                );
            }
            else if (q instanceof QuestaoAlternativa qa){
                PainelQuestoes.add(
                        new PainelQuestaoAlternativa(qa)
                );
            }
            else if (q instanceof QuestaoUpload qu){
                PainelQuestoes.add(
                        new PainelQuestaoUpload(qu)
                );
            }
            
        }
        PainelQuestoes.revalidate();
        PainelQuestoes.repaint();
    }
    
    private void configurarScroll() {

        painelCinza1.setPreferredSize(null);
        painelAzul1.setPreferredSize(null);

        PainelQuestoes.revalidate();
        painelCinza1.revalidate();
        painelAzul1.revalidate();

        jScrollPane6.setViewportView(painelAzul1);
        jScrollPane6.revalidate();
        jScrollPane6.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        painelAzul1 = new javax.swing.JPanel();
        painelCinza1 = new javax.swing.JPanel();
        titulo3 = new java.awt.Label();
        prazo = new java.awt.Label();
        btnEnviarTarefa2 = new javax.swing.JButton();
        PainelQuestoes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        painelAzul1.setBackground(new java.awt.Color(19, 112, 178));

        painelCinza1.setBackground(new java.awt.Color(217, 217, 217));

        titulo3.setAlignment(java.awt.Label.CENTER);
        titulo3.setBackground(new java.awt.Color(19, 112, 178));
        titulo3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 60)); // NOI18N
        titulo3.setForeground(new java.awt.Color(255, 255, 255));
        titulo3.setText("Questionário");

        prazo.setAlignment(java.awt.Label.CENTER);
        prazo.setBackground(new java.awt.Color(19, 112, 178));
        prazo.setForeground(new java.awt.Color(255, 255, 255));
        prazo.setText("Prazo: 01/01");

        btnEnviarTarefa2.setBackground(new java.awt.Color(240, 147, 32));
        btnEnviarTarefa2.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarTarefa2.setText("Enviar Tarefa");
        btnEnviarTarefa2.addActionListener(this::btnEnviarTarefa2ActionPerformed);

        PainelQuestoes.setBackground(new java.awt.Color(217, 217, 217));
        PainelQuestoes.setLayout(new javax.swing.BoxLayout(PainelQuestoes, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout PainelQuestoesLayout = new javax.swing.GroupLayout(PainelQuestoes);
        PainelQuestoes.setLayout(PainelQuestoesLayout);
        PainelQuestoesLayout.setHorizontalGroup(
            PainelQuestoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PainelQuestoesLayout.setVerticalGroup(
            PainelQuestoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelCinza1Layout = new javax.swing.GroupLayout(painelCinza1);
        painelCinza1.setLayout(painelCinza1Layout);
        painelCinza1Layout.setHorizontalGroup(
            painelCinza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCinza1Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(painelCinza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCinza1Layout.createSequentialGroup()
                        .addComponent(prazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnEnviarTarefa2))
                    .addGroup(painelCinza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(titulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                        .addComponent(PainelQuestoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 118, Short.MAX_VALUE))
        );
        painelCinza1Layout.setVerticalGroup(
            painelCinza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCinza1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(PainelQuestoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(painelCinza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarTarefa2))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout painelAzul1Layout = new javax.swing.GroupLayout(painelAzul1);
        painelAzul1.setLayout(painelAzul1Layout);
        painelAzul1Layout.setHorizontalGroup(
            painelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzul1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(painelCinza1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        painelAzul1Layout.setVerticalGroup(
            painelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzul1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(painelCinza1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(painelAzul1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarTarefa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarTarefa2ActionPerformed
        // TODO add your handling code her
        RespostaDAO respostaDAO = new RespostaDAO();
        for (Component c : PainelQuestoes.getComponents()) {

            Questao questao = null;
            if      (c instanceof PainelQuestaoDissertativa p) questao = p.getQuestao();
            else if (c instanceof PainelQuestaoAlternativa  p) questao = p.getQuestao();
            else if (c instanceof PainelQuestaoUpload       p) questao = p.getQuestao();
            if (questao == null) continue;

            Resposta resposta = new Resposta();
            resposta.setTentativa(tentativa);
            resposta.setQuestao(questao);
            resposta.setNota(0.0);
            respostaDAO.salvar(resposta); 

            if (c instanceof PainelQuestaoDissertativa painel) {
                RespostaDissertativa rd = new RespostaDissertativa();
                rd.setIdResposta(resposta.getIdResposta()); 
                rd.setTextoResposta(painel.getTextoResposta());
                new RespostaDissertativaDAO().salvar(rd);

            } else if (c instanceof PainelQuestaoAlternativa painel) {
                int idAlt = painel.getAlternativaSelecionada();
                if (idAlt == -1) {
                    JOptionPane.showMessageDialog(this, "Selecione uma alternativa antes de enviar.");
                    return;
                }
                RespostaAlternativa ra = new RespostaAlternativa();
                ra.setIdResposta(resposta.getIdResposta());
                ra.setIdAlternativa(idAlt);
                new RespostaAlternativaDAO().salvar(ra);

            } else if (c instanceof PainelQuestaoUpload painel) {
                try {
                    File arquivo = painel.getArquivoSelecionado();
                    if (arquivo == null) continue;


                    File pasta = new File("src/main/resources/aluno/");
                    if (!pasta.exists()) pasta.mkdirs();

                    RespostaUpload respostaUpload = new RespostaUpload();
                    File pastaUploads = new File(BASE_ALUNO);


                    String nomeArquivo = System.currentTimeMillis() + "_" + arquivo.getName();
                    ArquivoService.salvarArquivo(arquivo, new File(pasta, nomeArquivo));


                    RespostaUpload ru = new RespostaUpload();
                    ru.setIdResposta(resposta.getIdResposta()); 
                    ru.setArquivo(new File("uploads/" + nomeArquivo));
                    new RespostaUploadDAO().salvar(ru);

                    File destino = new File(
                            pastaUploads, nomeArquivo
                    );

                    ArquivoService.salvarArquivo(
                            arquivo, destino
                    );

                    respostaUpload.setArquivo(
                            destino
                    );

                    RespostaUploadDAO dao = new RespostaUploadDAO();
                    RespostaUploadDAO.salvar(respostaUpload);


                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro ao enviar arquivo: " + e.getMessage());
                }
            }
        }

        JOptionPane.showMessageDialog(this, "Tarefa enviada!");
    }//GEN-LAST:event_btnEnviarTarefa2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Tarefa tarefa = new Tarefa();
        tarefa.setIdTarefa(20);
        tarefa.setTitulo("Teste Geral");

        Aluno aluno = new Aluno();
        aluno.setIdAluno(9);

        Tentativa tentativa = new Tentativa(aluno, tarefa); 
        tentativa.registraTentativa();

        TelaQuestionarioAluno tqa = new TelaQuestionarioAluno(tarefa, tentativa, aluno);
        tqa.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelQuestoes;
    private javax.swing.JButton btnEnviarTarefa2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel painelAzul1;
    private javax.swing.JPanel painelCinza1;
    private java.awt.Label prazo;
    private java.awt.Label titulo3;
    // End of variables declaration//GEN-END:variables
}
