/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.presentation.TelaQuestionarioAluno;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.*;

import br.maua.domain.Aluno;
import br.maua.domain.Questao;
import br.maua.domain.QuestaoAlternativa;
import br.maua.domain.QuestaoDissertativa;
import br.maua.domain.QuestaoUpload;
import br.maua.domain.Tarefa;
import br.maua.domain.Tentativa;
import br.maua.domain.Usuario;
import br.maua.exception.UploadException;
import br.maua.infrastructure.DAO.*;
import br.maua.presentation.TelaQuestionarioAluno.Components.PainelQuestao;
import br.maua.presentation.TelaQuestionarioAluno.Components.PainelQuestaoAlternativa;
import br.maua.presentation.TelaQuestionarioAluno.Components.PainelQuestaoDissertativa;
import br.maua.presentation.TelaQuestionarioAluno.Components.PainelQuestaoUpload;
import br.maua.service.JornadaService;

/**
 *
 * @author Luiza
 */
public class TelaQuestionarioAluno extends JFrame {


    private static final Logger logger = Logger.getLogger
    (TelaQuestionarioAluno.class.getName());
    private final Tarefa tarefa;
    private final Usuario aluno;
    private final Tentativa tentativa;
    private final JFrame telaAnterior;
    private final List<PainelQuestao> respostas = new ArrayList<>();

    /**
     * Creates new form TelaQuestionarioAluno
     */
    public TelaQuestionarioAluno(Tarefa tarefa, Usuario usuario, JFrame telaAnterior) {
        this.telaAnterior = telaAnterior;
        this.tarefa = tarefa;
        this.aluno = usuario;

        if (usuario instanceof Aluno) {
            this.tentativa = new Tentativa((Aluno) usuario, tarefa);
        } else {
            this.tentativa = new Tentativa(new Aluno(), tarefa);
        }
        initComponents();
        try{
            QuestaoDAO.buscarPorTarefa(tarefa);
        }catch(SQLException e ){
            JOptionPane.showMessageDialog(rootPane, "Erro ao se comunicar com o banco!", "Erro", JOptionPane.ERROR_MESSAGE);
        }

        titulo3.setText(tarefa.getTitulo());

        try {

            java.util.Date prazoData = tarefa.getPrazo();

            if (prazoData != null) {

                java.text.SimpleDateFormat formatador = new java.text.SimpleDateFormat("dd/MM/yyyy");
                String prazoFormatado = formatador.format(prazoData);
                prazo.setText("Prazo: " + prazoFormatado);
            }

            else {
                prazo.setText("Prazo: Sem data");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        painelQuestao.setLayout(new BoxLayout(painelQuestao,BoxLayout.Y_AXIS));

        try {
            carregarQuestoes(tarefa.getQuestoes());
        } catch (Exception e) {
            e.printStackTrace();
        }

        painelAzul1.setLayout(new GridBagLayout());
        painelAzul1.add(painelCinza1);
        jScrollPane6.getVerticalScrollBar().setUnitIncrement(25);
        configurarScroll();

        boolean isProfessor = !(usuario instanceof Aluno) || usuario.getUsername().contains("professor"); 
        
        if (isProfessor) {
            btnEnviarTarefa2.setText("Fechar Visualização");
            btnEnviarTarefa2.setBackground(new Color(120, 120, 120));
        }
        
    }
    
    

    private void carregarQuestoes(List<Questao>questoes){
        for (Questao q : questoes){
            PainelQuestao painel = null;
            if (q instanceof QuestaoDissertativa qd){
                painel = new PainelQuestaoDissertativa(qd);
            }
            else if (q instanceof QuestaoAlternativa qa){
                painel = new PainelQuestaoAlternativa(qa);
            }
            else if (q instanceof QuestaoUpload qu){
                painel = new PainelQuestaoUpload(qu);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao carregar questões!", "Erro", JOptionPane.ERROR_MESSAGE);
            }

            respostas.add(painel);
            painelQuestao.add(painel);
        }
        painelQuestao.revalidate();
        painelQuestao.repaint();
    }
    
    private void configurarScroll() {

        painelCinza1.setPreferredSize(null);
        painelAzul1.setPreferredSize(null);

        painelQuestao.revalidate();
        painelCinza1.revalidate();
        painelAzul1.revalidate();

        jScrollPane6.setViewportView(painelAzul1);
        jScrollPane6.revalidate();
        jScrollPane6.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new JScrollPane();
        painelAzul1 = new JPanel();
        painelCinza1 = new JPanel();
        titulo3 = new Label();
        prazo = new Label();
        btnEnviarTarefa2 = new JButton();
        painelQuestao = new PainelQuestao();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jScrollPane6.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        painelAzul1.setBackground(new Color(19, 112, 178));

        painelCinza1.setBackground(new Color(217, 217, 217));

        titulo3.setAlignment(Label.CENTER);
        titulo3.setBackground(new Color(19, 112, 178));
        titulo3.setFont(new Font("Yu Gothic UI Semilight", 0, 60)); // NOI18N
        titulo3.setForeground(new Color(255, 255, 255));
        titulo3.setText("Questionário");

        prazo.setAlignment(Label.CENTER);
        prazo.setBackground(new Color(19, 112, 178));
        prazo.setForeground(new Color(255, 255, 255));
        prazo.setText("Prazo: 01/01");

        btnEnviarTarefa2.setBackground(new Color(240, 147, 32));
        btnEnviarTarefa2.setForeground(new Color(255, 255, 255));
        btnEnviarTarefa2.setText("Enviar Tarefa");
        btnEnviarTarefa2.addActionListener(this::btnEnviarTarefa2ActionPerformed);

        painelQuestao.setBackground(new Color(217, 217, 217));
        painelQuestao.setLayout(new BoxLayout(painelQuestao, BoxLayout.Y_AXIS));

        GroupLayout PainelQuestoesLayout = new GroupLayout(painelQuestao);
        painelQuestao.setLayout(PainelQuestoesLayout);
        PainelQuestoesLayout.setHorizontalGroup(
                PainelQuestoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PainelQuestoesLayout.setVerticalGroup(
                PainelQuestoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        GroupLayout painelCinza1Layout = new GroupLayout(painelCinza1);
        painelCinza1.setLayout(painelCinza1Layout);
        painelCinza1Layout.setHorizontalGroup(
                painelCinza1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(painelCinza1Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                    .addGroup(painelCinza1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(painelCinza1Layout.createSequentialGroup()
                            .addComponent(prazo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnEnviarTarefa2))
                            .addGroup(painelCinza1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(titulo3, GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                                    .addComponent(painelQuestao, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 118, Short.MAX_VALUE))
        );
        painelCinza1Layout.setVerticalGroup(
                painelCinza1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(painelCinza1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                    .addComponent(titulo3, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                    .addComponent(painelQuestao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                    .addGroup(painelCinza1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(prazo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarTarefa2))
                .addGap(51, 51, 51))
        );

        GroupLayout painelAzul1Layout = new GroupLayout(painelAzul1);
        painelAzul1.setLayout(painelAzul1Layout);
        painelAzul1Layout.setHorizontalGroup(
                painelAzul1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(painelAzul1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                    .addComponent(painelCinza1, GroupLayout.PREFERRED_SIZE, 930, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        painelAzul1Layout.setVerticalGroup(
                painelAzul1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(painelAzul1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                    .addComponent(painelCinza1, GroupLayout.PREFERRED_SIZE, 899, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(painelAzul1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarTarefa2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnEnviarTarefa2ActionPerformed
            if (btnEnviarTarefa2.getText().equals("Fechar Visualização")) {
                if (telaAnterior != null) {
                    br.maua.presentation.TelaNavegacao.abrir(this, telaAnterior);
                } else {
                    dispose(); 
        }
        return;
            }
            for (PainelQuestao resposta : respostas) {
                resposta.salvar(tentativa);
            }
            try {
                TentativaDAO.salvarTentativa(tentativa);
                JornadaService jornadaService = new JornadaService();
                jornadaService.avancarCasa(tentativa, this.tarefa.getCasa());
                JOptionPane.showMessageDialog(null, "Tentativa Salvo com sucesso!");
                dispose();
                telaAnterior.setVisible(true);
            } catch (SQLException | UploadException e) {
                logger.log(Level.SEVERE, e.getMessage());
                JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnEnviarTarefa2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        EventQueue.invokeLater(() -> {
            Tarefa tarefa = new Tarefa();
            tarefa.setIdTarefa(31);
            tarefa.setTitulo("Titulo Tarefa");
            Aluno aluno = new Aluno(14, "Pedro", "Sanches", "26.01461-3@maua.br");
            new TelaQuestionarioAluno(tarefa, aluno, new JFrame()).setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PainelQuestao painelQuestao;
    private JButton btnEnviarTarefa2;
    private JScrollPane jScrollPane6;
    private JPanel painelAzul1;
    private JPanel painelCinza1;
    private Label prazo;
    private Label titulo3;
    // End of variables declaration//GEN-END:variables
}
