/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package br.maua.presentation.TelaEscolhaDeQuestionario;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import br.maua.config.IconUtil;
import br.maua.domain.Usuario;
import br.maua.infrastructure.ConnectionFactory;

import javax.swing.*;

/**
 *
 * @author Luiza
 */
public class TelaEscolhaDeQuestionario extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                .getLogger(TelaEscolhaDeQuestionario.class.getName());
        private final JFrame telaAnterior;
        private final int idCasa;
        private final String tituloCasa;
        private final Usuario usuarioLogado;

        public TelaEscolhaDeQuestionario(Usuario usuario, int idCasa, String tituloCasa, JFrame telaAnterior) {
                this.telaAnterior = telaAnterior;
                this.usuarioLogado = usuario;
                this.idCasa = idCasa;
                this.tituloCasa = tituloCasa;
                this.setIconImages(IconUtil.ICONS);
                this.setTitle("Jornada Mauá");
                initComponents();

                nomeTitulo.setText(this.tituloCasa);

                carregarTarefas();
        }

        /**
         * This method is called from within the constructor to
         * initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                painelAzul = new javax.swing.JPanel();
                painelCinza = new javax.swing.JPanel();
                painelAzul1 = new javax.swing.JPanel();
                nomeTitulo = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                painelAzul.setBackground(new java.awt.Color(19, 112, 178));

                painelCinza.setBackground(new java.awt.Color(217, 217, 217));
                painelCinza.setMaximumSize(new java.awt.Dimension(900, 600));
                painelCinza.setMinimumSize(new java.awt.Dimension(900, 600));
                painelCinza.setLayout(null);

                painelAzul1.setBackground(new java.awt.Color(19, 112, 178));
                painelAzul1.setMaximumSize(new java.awt.Dimension(710, 90));
                painelAzul1.setMinimumSize(new java.awt.Dimension(710, 90));
                painelAzul1.setName(""); // NOI18N
                painelAzul1.setPreferredSize(new java.awt.Dimension(710, 90));

                nomeTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
                nomeTitulo.setForeground(new java.awt.Color(255, 255, 255));
                nomeTitulo.setText("Tarefas");
                nomeTitulo.setName("nomeTitulo"); // NOI18N

                javax.swing.GroupLayout painelAzul1Layout = new javax.swing.GroupLayout(painelAzul1);
                painelAzul1.setLayout(painelAzul1Layout);
                painelAzul1Layout.setHorizontalGroup(
                        painelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelAzul1Layout.createSequentialGroup()
                                        .addGap(271, 271, 271)
                                        .addComponent(nomeTitulo)
                                        .addContainerGap(301, Short.MAX_VALUE)));
                painelAzul1Layout.setVerticalGroup(
                        painelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelAzul1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(nomeTitulo)
                                        .addContainerGap(20, Short.MAX_VALUE)));

                painelCinza.add(painelAzul1);
                painelAzul1.setBounds(94, 37, 720, 90);

                jButton1.setBackground(new java.awt.Color(240, 147, 23));
                jButton1.setForeground(new java.awt.Color(255, 255, 255));
                jButton1.setText("Voltar");
                jButton1.setMaximumSize(new java.awt.Dimension(92, 33));
                jButton1.addActionListener(this::jButton1ActionPerformed);
                painelCinza.add(jButton1);
                jButton1.setBounds(20, 10, 72, 23);

                javax.swing.GroupLayout painelAzulLayout = new javax.swing.GroupLayout(painelAzul);
                painelAzul.setLayout(painelAzulLayout);
                painelAzulLayout.setHorizontalGroup(
                        painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAzulLayout
                                        .createSequentialGroup()
                                        .addContainerGap(78, Short.MAX_VALUE)
                                        .addComponent(painelCinza,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                900,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)));
                painelAzulLayout.setVerticalGroup(
                        painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelAzulLayout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(painelCinza,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                600,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(90, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(painelAzul, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE));
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(painelAzul, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                telaAnterior.setVisible(true);
                dispose();
        }// GEN-LAST:event_jButton1ActionPerformed

        private void carregarTarefas() {
                String sql = "SELECT id_tarefa, titulo_tarefa, prazo_tarefa " +
                        "FROM tarefa " +
                        "WHERE id_casa = ?";

                try (Connection con = ConnectionFactory.obterConexao();
                     PreparedStatement ps = con.prepareStatement(sql)) {

                        ps.setInt(1, idCasa);
                        ResultSet rs = ps.executeQuery();

                        int xInicial = 94;
                        int yInicial = 150;
                        int larguraCard = 720;
                        int alturaCard = 50;
                        int espacamento = 15;
                        int contador = 0;

                        boolean ehProfessor = usuarioLogado != null && usuarioLogado.ehProfessor();

                        while (rs.next()) {
                                int idTarefa = rs.getInt("id_tarefa");
                                String titulo = rs.getString("titulo_tarefa");
                                String prazoAtual = rs.getString("prazo_tarefa");

                                int posicaoY = yInicial + (contador * (alturaCard + espacamento));

                                javax.swing.JPanel cardTarefa = new javax.swing.JPanel();
                                cardTarefa.setBackground(new java.awt.Color(255, 255, 255));
                                cardTarefa.setLayout(null);
                                cardTarefa.setBounds(xInicial, posicaoY, larguraCard, alturaCard);
                                cardTarefa.setBorder(javax.swing.BorderFactory
                                        .createLineBorder(new java.awt.Color(19, 112, 178), 1));
                                cardTarefa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                                // Se for professor, reduzimos um pouco a largura do texto para não colidir com
                                // o botão laranja
                                int larguraLabelTexto = ehProfessor ? 530 : 660;

                                javax.swing.JLabel lblTitulo = new javax.swing.JLabel(titulo);
                                lblTitulo.setForeground(new java.awt.Color(19, 112, 178));
                                lblTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
                                lblTitulo.setBounds(20, 0, larguraLabelTexto, alturaCard);
                                cardTarefa.add(lblTitulo);

                                // CONTROLE DE ACESSO: O botão só é construído e inserido se for o professor
                                if (ehProfessor) {
                                        javax.swing.JButton btnAlterarData = new javax.swing.JButton("Alterar Data");
                                        btnAlterarData.setBackground(new java.awt.Color(240, 147, 32));
                                        btnAlterarData.setForeground(new java.awt.Color(255, 255, 255));
                                        btnAlterarData.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
                                        btnAlterarData.setBounds(larguraCard - 130 - 10, 8, 130, 34);
                                        cardTarefa.add(btnAlterarData);

                                        btnAlterarData.addActionListener(evt -> {
                                                try {
                                                        br.maua.domain.Tarefa tarefaParaModal = new br.maua.domain.Tarefa();
                                                        tarefaParaModal.setIdTarefa(idTarefa);
                                                        tarefaParaModal.setTitulo(titulo);

                                                        // Corrigido para passar "TelaEscolhaDeQuestionario.this"
                                                        // explicitamente no
                                                        // escopo da Runnable
                                                        br.maua.presentation.TelaEscolhaDeQuestionario.ModalAlterarPrazoTarefa modal = new br.maua.presentation.TelaEscolhaDeQuestionario.ModalAlterarPrazoTarefa(
                                                                TelaEscolhaDeQuestionario.this, true,
                                                                tarefaParaModal, prazoAtual);

                                                        modal.setLocationRelativeTo(TelaEscolhaDeQuestionario.this);
                                                        modal.setVisible(true);
                                                } catch (Exception e) {
                                                        e.printStackTrace();
                                                        javax.swing.JOptionPane.showMessageDialog(
                                                                TelaEscolhaDeQuestionario.this,
                                                                "Erro ao abrir o alterador de prazo.");
                                                }
                                        });
                                }

                                cardTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
                                        @Override
                                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                                try {
                                                        br.maua.domain.Tarefa tarefaCompleta = new br.maua.domain.Tarefa();
                                                        tarefaCompleta.setIdTarefa(idTarefa);
                                                        tarefaCompleta.setTitulo(titulo);

                                                        br.maua.infrastructure.DAO.QuestaoDAO
                                                                .buscarPorTarefa(tarefaCompleta);
                                                        br.maua.presentation.TelaQuestionarioAluno.TelaQuestionarioAluno telaQuestionario = new br.maua.presentation.TelaQuestionarioAluno.TelaQuestionarioAluno(
                                                                tarefaCompleta, usuarioLogado,
                                                                TelaEscolhaDeQuestionario.this);
                                                        br.maua.presentation.TelaNavegacao.abrir(
                                                                TelaEscolhaDeQuestionario.this,
                                                                telaQuestionario);
                                                } catch (Exception e) {
                                                        e.printStackTrace();
                                                        javax.swing.JOptionPane.showMessageDialog(
                                                                TelaEscolhaDeQuestionario.this,
                                                                "Erro ao abrir o questionário: "
                                                                        + e.getMessage(),
                                                                "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
                                                }
                                        }
                                });

                                painelCinza.add(cardTarefa);
                                contador++;
                        }
                        painelCinza.revalidate();
                        painelCinza.repaint();
                } catch (SQLException e) {
                        logger.log(java.util.logging.Level.SEVERE, "Erro ao carregar tarefas", e);
                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel nomeTitulo;
        private javax.swing.JPanel painelAzul;
        private javax.swing.JPanel painelAzul1;
        private javax.swing.JPanel painelCinza;
        // End of variables declaration//GEN-END:variables

}
