/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.maua.presentation.TelaQuestionarioAluno.Components;

import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import br.maua.domain.RespostaUpload;
import br.maua.domain.Tentativa;
import br.maua.domain.QuestaoUpload;
import br.maua.presentation.TelaQuestionarioAluno.TelaQuestionarioAluno;
import br.maua.service.ArquivoService;

/**
 *
 * @author Luiza
 */
public class PainelQuestaoUpload extends PainelQuestao {
    private final QuestaoUpload questao;
    private final File arquivoProfessor;
    private File uploadAluno;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaQuestionarioAluno.class.getName());
    /**
     * Creates new form PainelQuestaoUpload
     */
    public PainelQuestaoUpload(QuestaoUpload questao) {
        this.questao = questao;
        initComponents();
        jTextPane4.setEditable(false);
        jTextPane4.setFocusable(false);
        jTextPane4.setText(
                questao.getEnunciado()
        );
        this.arquivoProfessor = questao.getArquivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelUpload = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        btnDownload = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();

        PainelUpload.setBackground(new java.awt.Color(217, 217, 217));

        jTextPane4.setEditable(false);
        jTextPane4.setBackground(new java.awt.Color(19, 112, 178));
        jTextPane4.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jTextPane4);

        btnDownload.setBackground(new java.awt.Color(19, 112, 178));
        btnDownload.setForeground(new java.awt.Color(255, 255, 255));
        btnDownload.setText("Download do arquivo");
        btnDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDownload.addActionListener(this::btnDownloadActionPerformed);

        btnUpload.setBackground(new java.awt.Color(240, 147, 32));
        btnUpload.setForeground(new java.awt.Color(255, 255, 255));
        btnUpload.setText("Upload de arquivo");
        btnUpload.addActionListener(this::btnUploadActionPerformed);

        javax.swing.GroupLayout PainelUploadLayout = new javax.swing.GroupLayout(PainelUpload);
        PainelUpload.setLayout(PainelUploadLayout);
        PainelUploadLayout.setHorizontalGroup(
            PainelUploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addComponent(btnDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
            .addComponent(btnUpload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelUploadLayout.setVerticalGroup(
            PainelUploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelUploadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelUpload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelUpload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        // TODO add your handling code here:

            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Salvar arquivo");
        chooser.setSelectedFile(new File(arquivoProfessor.getName()));

            int opcao = chooser.showSaveDialog(this);

            if (opcao == JFileChooser.APPROVE_OPTION) {
                File destino = chooser.getSelectedFile();
                String nome = destino.getName();
                int index = nome.lastIndexOf('.');
                boolean hasExtensao = index != -1;

                if (!hasExtensao) {

                    int indexOriginal = arquivoProfessor.getName().lastIndexOf('.');
                    String extensao = arquivoProfessor.getName().substring(indexOriginal);

                    destino = new File(destino.getPath() + extensao);
                }

                // Copia do InputStream para o destino
                ArquivoService.salvarArquivo(arquivoProfessor, destino);

                JOptionPane.showMessageDialog(this, "Download concluído!");
            }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            uploadAluno = fileChooser.getSelectedFile();
            System.out.println("Arquivo selecionado: " + uploadAluno.getAbsolutePath());
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    @Override
    public QuestaoUpload getQuestao() {
        return questao;
    }

    public File getUploadAluno() {
        return uploadAluno;
    }

    public void salvar(Tentativa tentativa) {
        tentativa.getRespostas().add(new RespostaUpload(tentativa, questao, getUploadAluno()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelUpload;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnUpload;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane4;
    // End of variables declaration//GEN-END:variables
}
