/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package br.maua.presentation.TelaAlunosDaTurma;

import br.maua.config.IconUtil;
import br.maua.domain.Aluno;
import br.maua.domain.Turma;
import br.maua.infrastructure.DAO.TurmaDAO;
import br.maua.presentation.TelaAdicionarAlunoNaTurma.ModalRegistrarAlunoTurma;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author marjo
 */
public class TelaAlunosDaTurma extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                .getLogger(TelaAlunosDaTurma.class.getName());
        private final Turma turma;
        private final JFrame telaAnterior;

        /**
         * Creates new form TelaAlunosDaTurma
         */
        public TelaAlunosDaTurma(Turma turma, JFrame telaAnterior) {
                this.turma = turma;
                this.telaAnterior = telaAnterior;
                this.setIconImages(IconUtil.ICONS);
                this.setTitle("Jornada Mauá");
                initComponents();
                carregarAlunos(this);
                jLabel1.setText(turma.toString());

        }

        /**
         * This method is called from within the constructor to
         * initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                buttonAddAluno = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                buttonVoltar = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setSize(new java.awt.Dimension(1048, 768));

                jPanel1.setBackground(new java.awt.Color(30, 100, 180));
                jPanel1.setPreferredSize(new java.awt.Dimension(1048, 768));

                jPanel2.setBackground(new java.awt.Color(210, 210, 210));
                jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
                jPanel2.setPreferredSize(new java.awt.Dimension(950, 610));

                jLabel1.setBackground(new java.awt.Color(220, 140, 30));
                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("NomeDaTurma");
                jLabel1.setOpaque(true);

                buttonAddAluno.setBackground(new java.awt.Color(220, 140, 30));
                buttonAddAluno.setForeground(new java.awt.Color(255, 255, 255));
                buttonAddAluno.setText("Adicionar Aluno");
                buttonAddAluno.setOpaque(true);
                buttonAddAluno.addActionListener(this::buttonAddAlunoActionPerformed);

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null}
                        },
                        new String[]{
                                "Nome", "RA", "Atividades Feitas"
                        }));
                jScrollPane1.setViewportView(jTable1);

                buttonVoltar.setBackground(new java.awt.Color(220, 140, 30));
                buttonVoltar.setForeground(new java.awt.Color(255, 255, 255));
                buttonVoltar.setText("Voltar");
                buttonVoltar.setOpaque(true);
                buttonVoltar.addActionListener(this::buttonVoltarActionPerformed);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel2Layout.createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        jPanel2Layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jScrollPane1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        846,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout
                                                        .createSequentialGroup()
                                                        .addComponent(buttonVoltar)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(buttonAddAluno)
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                        .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                66,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(buttonAddAluno)
                                                .addComponent(buttonVoltar))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                        .createSequentialGroup()
                                        .addContainerGap(47, Short.MAX_VALUE)
                                        .addComponent(jPanel2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)));
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                        .createSequentialGroup()
                                        .addContainerGap(34, Short.MAX_VALUE)
                                        .addComponent(jPanel2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)));

                getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void buttonAddAlunoActionPerformed(java.awt.event.ActionEvent evt) {
                java.awt.EventQueue.invokeLater(() -> {
                        new ModalRegistrarAlunoTurma(this, true, turma).setVisible(true);
                });
        }

        private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonVoltarActionPerformed
                telaAnterior.setVisible(true);
                dispose();
        }// GEN-LAST:event_buttonVoltarActionPerformed

        private void carregarAlunos(JFrame telaAnterior) {
                DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                        new String[]{"Nome", "RA", "Média", "Atividades"},
                        0) {
                        @Override
                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return columnIndex == 3;
                        }
                };

                jTable1.setModel(modelo);
                new SwingWorker<List<Aluno>, Void>() {
                        @Override
                        protected List<Aluno> doInBackground() throws Exception {
                                return TurmaDAO.buscaAlunos(turma);
                        }

                        @Override
                        protected void done() {
                                try {
                                        List<Aluno> alunos = get();
                                        for (Aluno aluno : alunos) {
                                                modelo.addRow(new Object[]{
                                                        aluno,
                                                        aluno.getRa(),
                                                        aluno.getMedia(),
                                                        "Acessar"
                                                });
                                        }
                                        jTable1.getColumn("Atividades")
                                                .setCellRenderer(new ButtonRenderer());
                                        jTable1.getColumn("Atividades")
                                                .setCellEditor(new ButtonAcessarTarefasAluno(new JCheckBox(),
                                                        jTable1, telaAnterior));
                                } catch (Exception ex) {
                                        Logger.getLogger(TelaAlunosDaTurma.class.getName()).log(Level.SEVERE, null, ex);
                                        JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro",
                                                JOptionPane.ERROR_MESSAGE);
                                }
                        }
                }.execute();
        }

        public void recarregarTabela() {
                carregarAlunos(telaAnterior);
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton buttonAddAluno;
        private javax.swing.JButton buttonVoltar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        // End of variables declaration//GEN-END:variables

}
