package br.maua.presentation.TelaAdicionarAlunoNaTurma;

import br.maua.domain.Aluno;
import br.maua.domain.Turma;
import br.maua.infrastructure.DAO.AlunoDAO;
import br.maua.infrastructure.DAO.TurmaDAO;
import br.maua.presentation.TelaAlunosDaTurma.TelaAlunosDaTurma;

import java.awt.event.WindowEvent;

import javax.swing.*;

/**
 *
 * @author Lenovo
 */
public class TelaAdicionarAlunoNaTurma extends javax.swing.JFrame {

    private final TelaAlunosDaTurma telaAnterior;
    private int idTurma;
    private int idSubturma;
    private int idCurso;
    private int idSemestre;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAdicionarAlunoNaTurma.class.getName());
    private final JFrame telaAnterior;
    /**
     * Creates new form TelaAdicionarAlunoNaTurma
     */
    public TelaAdicionarAlunoNaTurma(TelaAlunosDaTurma telaAnterior) {
        initComponents();
        this.telaAnterior = telaAnterior;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent we) {

                if (telaAnterior != null) {
                    telaAnterior.atualizarTabelaAlunosTurma();
                    telaAnterior.setVisible(true);
                }
            }
        });
    }

    public TelaAdicionarAlunoNaTurma() {
    public TelaAdicionarAlunoNaTurma(JFrame telaAnterior) {
        this.telaAnterior = telaAnterior;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
            buttonAdicionar = new javax.swing.JButton();
            jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(19, 112, 178));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adicionar Aluno");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");

            buttonAdicionar.setText("Adicionar");
            buttonAdicionar.addActionListener(this::buttonAdicionarActionPerformed);

            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAdicionar)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(89, 89, 89)
                .addComponent(jLabel5)
                    .addGap(78, 78, 78)
                    .addComponent(buttonAdicionar)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void buttonAdicionarActionPerformed (java.awt.event.ActionEvent evt)
        {//GEN-FIRST:event_buttonAdicionarActionPerformed

            String nome = campoNome.getText().trim();
            String sobrenome = campoSobrenome.getText().trim();
            String username = campoUsername.getText().trim();

            if (nome.isEmpty() || sobrenome.isEmpty() || username.isEmpty()) {

                javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
                return;

            }

            AlunoDAO alunoDAO = new AlunoDAO();
            TurmaDAO turmaDAO = new TurmaDAO();

            try {

                String tipoUsuario = alunoDAO.determinarTipoUsuario(username);
                if (tipoUsuario == null || tipoUsuario.trim().isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Username não encontrado!");
                    return;
                }
                if (!"aluno".equalsIgnoreCase(tipoUsuario)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Tipo de usuário incompatível!");
                    return;
                }

                Aluno aluno = alunoDAO.obterAlunoPelaTelaAdicionarAlunoNaTurma(nome, sobrenome, username);

                if (aluno == null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
                    return;
                }

                boolean sucesso = turmaDAO.vincularAluno(aluno.getIdAluno(), this.telaAnterior.getIdTurma(), this.telaAnterior.getIdSubturma(), this.telaAnterior.getIdCurso(), this.telaAnterior.getIdSemestre());

                if (sucesso) {

                    javax.swing.JOptionPane.showMessageDialog(this, "Aluno adicionado com sucesso!");
                    this.dispose();

                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Não foi possível adicionar o aluno na turma!");
                }
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }//GEN-LAST:event_buttonAdicionarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main (String[]args){
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> new TelaAdicionarAlunoNaTurma().setVisible(true));
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton buttonAdicionar;
        private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
