/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.presentation.TelaTarefasAluno;

import br.maua.infrastructure.ConnectionFactory;
import br.maua.presentation.TelaQuestionarioAluno.TelaQuestionarioAluno;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class TelaTarefaAluno extends javax.swing.JFrame {
    
    private final Integer idAluno;
    private final Integer idCasa;
    private final String tituloTarefa;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaTarefaAluno.class.getName());

    /**
     * Creates new form TelaTarefaAluno
     */
    public TelaTarefaAluno() {
        this(null, null, "Atividade");
    }

    public TelaTarefaAluno(String tituloTarefa) {
        this(null, null, tituloTarefa);
    }

    public TelaTarefaAluno(Integer idAluno, Integer idCasa, String tituloTarefa) {
        this.idAluno = idAluno;
        this.idCasa = idCasa;
        this.tituloTarefa = tituloTarefa != null && !tituloTarefa.isBlank() ? tituloTarefa : "Atividade";
        initComponents();
        configurarConteudo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        painelCinza = new javax.swing.JPanel();
        Atividade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(19, 112, 178));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tarefas");

        jButton2.setText("Voltar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        painelCinza.setBackground(new java.awt.Color(217, 217, 217));

        Atividade.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        Atividade.setText("Atividade:");

        jButton3 = new javax.swing.JButton();
        jButton3.setText("Questionário");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout painelCinzaLayout = new javax.swing.GroupLayout(painelCinza);
        painelCinza.setLayout(painelCinzaLayout);
        painelCinzaLayout.setHorizontalGroup(
            painelCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCinzaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Atividade, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(527, Short.MAX_VALUE))
        );
        painelCinzaLayout.setVerticalGroup(
            painelCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCinzaLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(Atividade)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton2)
                        .addGap(277, 277, 277)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(painelCinza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(painelCinza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarConteudo() {
        painelCinza.removeAll();
        painelCinza.setLayout(new BoxLayout(painelCinza, BoxLayout.Y_AXIS));
        painelCinza.setBorder(BorderFactory.createEmptyBorder(18, 18, 18, 18));

        JLabel titulo = new JLabel(this.tituloTarefa);
        titulo.setFont(new Font("Segoe UI", Font.BOLD, 24));
        titulo.setForeground(new Color(19, 112, 178));
        titulo.setAlignmentX(LEFT_ALIGNMENT);

        JLabel subtitulo = new JLabel(idCasa != null ? "Casa " + idCasa : "Tarefas disponíveis");
        subtitulo.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        subtitulo.setForeground(new Color(80, 80, 80));
        subtitulo.setAlignmentX(LEFT_ALIGNMENT);

        painelCinza.add(titulo);
        painelCinza.add(Box.createRigidArea(new Dimension(0, 8)));
        painelCinza.add(subtitulo);
        painelCinza.add(Box.createRigidArea(new Dimension(0, 14)));

        List<RegistroTarefaAluno> tarefas = carregarTarefasDaCasa();
        if (tarefas.isEmpty()) {
            JLabel vazio = new JLabel("Nenhuma tarefa encontrada para esta casa.");
            vazio.setFont(new Font("Segoe UI", Font.PLAIN, 16));
            vazio.setForeground(new Color(90, 90, 90));
            vazio.setAlignmentX(LEFT_ALIGNMENT);
            painelCinza.add(vazio);
        } else {
            for (RegistroTarefaAluno tarefa : tarefas) {
                painelCinza.add(criarCardTarefa(tarefa));
                painelCinza.add(Box.createRigidArea(new Dimension(0, 12)));
            }
        }

        painelCinza.revalidate();
        painelCinza.repaint();
    }

    private List<RegistroTarefaAluno> carregarTarefasDaCasa() {
        List<RegistroTarefaAluno> tarefas = new ArrayList<>();
        if (idCasa == null) {
            return tarefas;
        }

        String sql = "SELECT t.id_tarefa, t.titulo_tarefa, COUNT(te.id_tentativa) AS total_tentativas "
            + "FROM tarefa t "
            + "LEFT JOIN tentativa te ON te.id_tarefa = t.id_tarefa "
            + (idAluno != null ? "AND te.id_usuario = ? " : "")
            + "WHERE t.id_casa = ? "
            + "GROUP BY t.id_tarefa, t.titulo_tarefa "
            + "ORDER BY t.id_tarefa";

        try (Connection conexao = ConnectionFactory.obterConexao();
             PreparedStatement comando = conexao.prepareStatement(sql)) {

            int index = 1;
            if (idAluno != null) {
                comando.setInt(index++, idAluno);
            }
            comando.setInt(index, idCasa);

            try (ResultSet resultado = comando.executeQuery()) {
                while (resultado.next()) {
                    tarefas.add(new RegistroTarefaAluno(
                        resultado.getInt("id_tarefa"),
                        resultado.getString("titulo_tarefa"),
                        resultado.getInt("total_tentativas")
                    ));
                }
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar tarefas: " + e.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        return tarefas;
    }

    private JPanel criarCardTarefa(RegistroTarefaAluno tarefa) {
        JPanel card = new JPanel(new BorderLayout(10, 8));
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(240, 147, 32), 2),
            BorderFactory.createEmptyBorder(14, 16, 14, 16)));
        card.setAlignmentX(LEFT_ALIGNMENT);

        JLabel titulo = new JLabel(tarefa.tituloTarefa);
        titulo.setFont(new Font("Segoe UI", Font.BOLD, 18));
        titulo.setForeground(new Color(19, 112, 178));

        JLabel id = new JLabel("Tarefa #" + tarefa.idTarefa);
        id.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        id.setForeground(new Color(100, 100, 100));

        JLabel tentativas = new JLabel("Tentativas: " + tarefa.totalTentativas);
        tentativas.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        tentativas.setForeground(new Color(100, 100, 100));

        JButton abrir = new JButton("Questionário");
        abrir.setBackground(new Color(240, 147, 32));
        abrir.setForeground(Color.WHITE);
        abrir.setFocusPainted(false);
        abrir.addActionListener(evt -> abrirQuestionarioAluno());

        JPanel textos = new JPanel();
        textos.setOpaque(false);
        textos.setLayout(new BoxLayout(textos, BoxLayout.Y_AXIS));
        textos.add(titulo);
        textos.add(Box.createRigidArea(new Dimension(0, 4)));
        textos.add(id);
        textos.add(Box.createRigidArea(new Dimension(0, 2)));
        textos.add(tentativas);

        card.add(textos, BorderLayout.CENTER);
        card.add(abrir, BorderLayout.EAST);
        return card;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Voltar para o tabuleiro
        br.maua.presentation.TelaNavegacao.voltar(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TelaQuestionarioAluno questionario = new TelaQuestionarioAluno();
        br.maua.presentation.TelaNavegacao.abrir(this, questionario);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void abrirQuestionarioAluno() {
        TelaQuestionarioAluno questionario = new TelaQuestionarioAluno();
        br.maua.presentation.TelaNavegacao.abrir(this, questionario);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaTarefaAluno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atividade;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelCinza;
    // End of variables declaration//GEN-END:variables

    private static final class RegistroTarefaAluno {
        private final int idTarefa;
        private final String tituloTarefa;
        private final int totalTentativas;

        private RegistroTarefaAluno(int idTarefa, String tituloTarefa, int totalTentativas) {
            this.idTarefa = idTarefa;
            this.tituloTarefa = tituloTarefa;
            this.totalTentativas = totalTentativas;
        }
    }
}
